
name: CI

on:
  push:
    branches:
    - feature/test-ignore-failing


jobs:
  test-run:
    runs-on: ubuntu-latest
    name: test-run
    steps:
      - name: Fail but ignore
        run: |
          qwerty
          # Try to ignore failiure
          exit 0
